app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%locales%'

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        permanent: true
        route: app_dashboard_calendar
